### PR TITLE
quick and dirty custom category template

### PR DESCRIPTION
**Pull request by jesilz**

### CODE REVIEW

**Comment by jesilz** [comment]
@timbeardshear Use this to test custom site category templates

Create view files at `app/views/categories/templates/:site.slug/:category.slug`

Example: A custom template for the GRIT "Insight" category would be stored at `app/views/categories/templates/grit/insight.html.slim`

**Comment by halloffame** [comment]
This looks good to me. I'm not sure why the error, it looks like it is coming from elasticsearch.

**Comment by timbeardshear** [comment]
@jesilz Thanks. What's the best way to get this up on staging at the same time as my updates on the "grit_updates" branch? Can this be merged into master?

**Comment by jesilz** [comment]
@timbeardshear it looks like you merged this into your Grit branch. If that's the case, can we close and delete this branch?

**Comment by timbeardshear** [comment]
@jesilz Yes, I think this branch can be removed.

**Pull request closed without merging**
